AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cl

  Sample SAM Template for cl

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 650

Resources:
  RecapEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: recap_email/
      Handler: app.app.handler
      Runtime: python3.11
      Environment:
        Variables:
          RECAP_EMAIL_ENDPOINT: https://www.courtlistener.com/api/rest/v3/recap-email/
          AUTH_TOKEN: xxxxxxxxxxxxxxxxxxxxxxx
          SENTRY_DSN: ""
      Events:
        RecapEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recap-email
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RecapEmailApi:
    Description: "API Gateway endpoint URL for Prod stage for Free Look function"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/recap-email/"
  RecapEmailFunction:
    Description: "Free Look Email Lambda Function ARN"
    Value:
      Fn::GetAtt: RecapEmailFunction.Arn
  RecapEmailFunctionIamRole:
    Description: "Implicit IAM Role created for the Free Look Email function"
    Value:
      Fn::GetAtt: RecapEmailFunctionRole.Arn
