name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - uses: pre-commit/action@v3.0.1

      - name: Install Python dependencies
        run: |
          cd cl
          uv pip install --system -r recap_email/requirements.txt -r tests/requirements.txt

      - name: mypy Static Type Checker
        run: mypy --ignore-missing-imports .
