name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: pre-commit/action@v3.0.1

      - name: Install dependencies
        run: cd cl && pip install -r recap_email/requirements.txt && pip install -r tests/requirements.txt

      - name: mypy Static Type Checker
        run: mypy --ignore-missing-imports .
